hcloud_token = "rUYukxeMtm6SseThAuWTfhwNxfyJ9q2V1AhWvstqdRAQlUc6jZsfPeBJWRCDy2EW"
docker_version = "19"
rancher_version = "v2.4.5"
ssh_key_name = "admin@rancher.mobilelife.de"
ssh_public_key = ".ssh/id_rsa.pub"
ssh_private_key = ".ssh/id_rsa"
rancher_password = "2ymhqjrd"
rancher_cluster_name = "playground"
#https://github.com/rancher/hyperkube/releases
rancher_kubernetes_version = "v1.18.3-rancher2-2"
acme_domain = "rancher.mobilelife.de"
